/**
 * IntelligenceContext.jsx
 *
 * THE CORE STATE ENGINE OF VISIONOPS.
 *
 * This context is the single source of truth for the entire application.
 * It owns:
 *   - isMonitoring: Whether the webcam inference loop is active.
 *   - latestDetections: The most recent array of objects returned by the model.
 *   - eventHistory: A persistent log of every detection event (used by the feed + investigation).
 *   - currentLatency: The round-trip time of the last inference call in milliseconds.
 *   - fps: Calculated frames-per-second of the inference loop.
 *   - systemStatus: High-level health indicators for the status bar.
 *
 * DATA FLOW:
 *   LiveMonitoring (produces data) → IntelligenceContext (stores data) → OperationsCenter (consumes data)
 *
 * This ensures the Intelligence Feed in OperationsCenter automatically updates
 * with real events generated by the webcam inference loop in LiveMonitoring.
 */

import React, { createContext, useContext, useState, useCallback, useRef } from 'react';

const IntelligenceContext = createContext(null);

// Color assignment per object class for bounding box rendering
export const CLASS_COLORS = {
  person:        '#22C55E', // emerald-500
  laptop:        '#3B82F6', // blue-500
  'cell phone':  '#A855F7', // purple-500
  bottle:        '#06B6D4', // cyan-500
  chair:         '#F59E0B', // amber-500
  monitor:       '#3B82F6', // blue-500
  'tv':          '#3B82F6',
  mouse:         '#EC4899', // pink-500
  keyboard:      '#8B5CF6', // violet-500
  book:          '#F97316', // orange-500
  cup:           '#14B8A6', // teal-500
  'dining table':'#84CC16', // lime-500
  default:       '#64748B', // slate-500
};

export const getClassColor = (label) =>
  CLASS_COLORS[label?.toLowerCase()] || CLASS_COLORS.default;

// Maximum events to keep in history
const MAX_HISTORY = 100;

export function IntelligenceProvider({ children }) {
  const [isMonitoring, setIsMonitoring] = useState(false);
  const [latestDetections, setLatestDetections] = useState([]);
  const [eventHistory, setEventHistory] = useState([]);
  const [currentLatency, setCurrentLatency] = useState(null);
  const [fps, setFps] = useState(0);
  const [systemStatus, setSystemStatus] = useState({
    cameraConnected: false,
    modelConnected: false,
    monitoringActive: false,
    totalDetections: 0,
    monitoringStartTime: null,
  });

  // Cooldown registry: tracks the last time each class was added as an event.
  // Prevents event spam (e.g., 30 "person detected" entries per second).
  const cooldownRef = useRef({});
  const COOLDOWN_MS = 4000; // Min gap between same-class events

  // Previous detection set for "left scene" tracking
  const prevDetectedClassesRef = useRef(new Set());

  /**
   * generateEvents (Operational Risk Engine)
   *
   * Transforms raw bounding boxes into business logic events.
   */
  const generateEvents = useCallback((detections, snapshot) => {
    const now = Date.now();
    const newEvents = [];
    const currentClasses = new Set(detections.map(d => d.label));
    
    // --- Rule Engine Evaluation ---
    
    // 1. Count objects
    const personDetections = detections.filter(d => d.label === 'person');
    const laptopDetections = detections.filter(d => d.label === 'laptop');
    const phoneDetections = detections.filter(d => d.label === 'cell phone');
    
    const rulesTriggered = [];

    // Rule 1: Occupancy Event
    if (personDetections.length > 0) {
      rulesTriggered.push({
        id: 'rule-occupancy',
        ruleName: 'Occupancy Event',
        severity: 'info',
        reason: `${personDetections.length} person(s) detected in zone.`,
        action: 'Log occupancy duration.',
        label: 'person',
      });
    }

    // Rule 2: Overcrowding Risk
    if (personDetections.length > 8) {
      rulesTriggered.push({
        id: 'rule-overcrowding',
        ruleName: 'Overcrowding Risk',
        severity: 'warning',
        reason: `Capacity exceeded: ${personDetections.length} persons detected (Threshold: 8).`,
        action: 'Dispatch facility manager to check ventilation/capacity.',
        label: 'person',
      });
    }

    // Rule 3: Unattended Asset
    if (laptopDetections.length > 0 && personDetections.length === 0) {
      rulesTriggered.push({
        id: 'rule-unattended-asset',
        ruleName: 'Potential Unattended Asset',
        severity: 'warning',
        reason: `${laptopDetections.length} laptop(s) detected with no personnel present.`,
        action: 'Alert security desk to secure high-value assets.',
        label: 'laptop',
      });
    }

    // Rule 4: Mobile Device Density Alert
    if (phoneDetections.length >= 3) {
      rulesTriggered.push({
        id: 'rule-phone-density',
        ruleName: 'Mobile Device Density Alert',
        severity: 'info',
        reason: `High concentration of mobile devices (${phoneDetections.length}).`,
        action: 'Monitor for unauthorized recording or secure facility breach.',
        label: 'cell phone',
      });
    }

    // Rule 5: Review Required (Unknown/Unusual Objects)
    const unusualObjects = detections.filter(d => ['backpack', 'suitcase', 'handbag', 'umbrella'].includes(d.label));
    if (unusualObjects.length > 0) {
      const labels = unusualObjects.map(d => d.label).join(', ');
      rulesTriggered.push({
        id: 'rule-review-required',
        ruleName: 'Review Required',
        severity: 'critical',
        reason: `Unusual objects detected: ${labels}.`,
        action: 'Investigate potential security threat or left baggage.',
        label: unusualObjects[0].label,
      });
    }

    // Process triggered rules through cooldown registry to prevent spam
    for (const rule of rulesTriggered) {
      const lastFired = cooldownRef.current[rule.id] || 0;
      // 5-second cooldown per rule
      if (now - lastFired >= 5000) {
        cooldownRef.current[rule.id] = now;
        
        newEvents.push({
          id: `${now}-${rule.id}`,
          timestamp: new Date().toISOString(),
          type: rule.severity === 'critical' ? 'critical' : rule.severity === 'warning' ? 'warning' : 'info',
          zone: 'Monitoring Zone A',
          label: rule.label,
          confidence: null, // Rules are aggregated
          message: rule.reason,
          ruleName: rule.ruleName,
          recommendedAction: rule.action,
          snapshot,
          allDetections: detections,
        });
      }
    }

    prevDetectedClassesRef.current = currentClasses;

    if (newEvents.length > 0) {
      setEventHistory(prev => [
        ...newEvents,
        ...prev,
      ].slice(0, MAX_HISTORY));
    }
  }, []);

  const startMonitoring = useCallback(() => {
    setIsMonitoring(true);
    setSystemStatus(s => ({
      ...s,
      cameraConnected: true,
      modelConnected: true,
      monitoringActive: true,
      monitoringStartTime: Date.now(),
    }));
  }, []);

  const stopMonitoring = useCallback(() => {
    setIsMonitoring(false);
    setLatestDetections([]);
    setFps(0);
    setCurrentLatency(null);
    prevDetectedClassesRef.current = new Set();
    cooldownRef.current = {};
    setSystemStatus(s => ({
      ...s,
      cameraConnected: false,
      monitoringActive: false,
    }));
  }, []);

  const pushDetectionResult = useCallback(({ detections, latencyMs, snapshot }) => {
    setLatestDetections(detections);
    setCurrentLatency(latencyMs);
    setSystemStatus(s => ({
      ...s,
      totalDetections: s.totalDetections + detections.length,
    }));
    generateEvents(detections, snapshot);
  }, [generateEvents]);

  const updateFps = useCallback((value) => {
    setFps(value);
  }, []);

  return (
    <IntelligenceContext.Provider value={{
      isMonitoring,
      latestDetections,
      eventHistory,
      currentLatency,
      fps,
      systemStatus,
      startMonitoring,
      stopMonitoring,
      pushDetectionResult,
      updateFps,
    }}>
      {children}
    </IntelligenceContext.Provider>
  );
}

export function useIntelligence() {
  const ctx = useContext(IntelligenceContext);
  if (!ctx) throw new Error('useIntelligence must be used inside IntelligenceProvider');
  return ctx;
}

function capitalize(str) {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
}
